# Generated by Django 3.2.2 on 2021-07-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emppersonal',
            name='user',
        ),
    ]
